/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/data/coreutils"
#define EXEC_PREFIX "/data/coreutils"
#define BINDIR "/data/coreutils/bin"
#define SBINDIR "/data/coreutils/sbin"
#define LIBEXECDIR "/data/coreutils/libexec"
#define DATAROOTDIR "/data/coreutils/share"
#define DATADIR "/data/coreutils/share"
#define SYSCONFDIR "/data/coreutils/etc"
#define SHAREDSTATEDIR "/data/coreutils/com"
#define LOCALSTATEDIR "/data/coreutils/var"
#define RUNSTATEDIR "/data/coreutils/var/run"
#define INCLUDEDIR "/data/coreutils/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/data/coreutils/share/doc/coreutils"
#define INFODIR "/data/coreutils/share/info"
#define HTMLDIR "/data/coreutils/share/doc/coreutils"
#define DVIDIR "/data/coreutils/share/doc/coreutils"
#define PDFDIR "/data/coreutils/share/doc/coreutils"
#define PSDIR "/data/coreutils/share/doc/coreutils"
#define LIBDIR "/data/coreutils/lib"
#define LISPDIR "/data/coreutils/share/emacs/site-lisp"
#define LOCALEDIR "/data/coreutils/share/locale"
#define MANDIR "/data/coreutils/share/man"
#define PKGDATADIR "/data/coreutils/share/coreutils"
#define PKGINCLUDEDIR "/data/coreutils/include/coreutils"
#define PKGLIBDIR "/data/coreutils/lib/coreutils"
#define PKGLIBEXECDIR "/data/coreutils/libexec/coreutils"
